[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

#インサートモードに入ったら読み込む
[[plugins]]
repo = 'Shougo/neocomplete.vim' #補完
on-i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'
