[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

#インサートモードに入ったら読み込む
[[plugins]]
repo = 'Shougo/neocomplete.vim' #補完
on-i = 1

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_source = ['neocomplete.vim']
