#インサートモードに入ったら読み込む
[[plugins]]
repo = 'Shougo/neocomplete.vim' #補完
on-i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

#-python---
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

#-ruby-----
[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['ruby']

#rubocop
[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = ['ruby']
hook_post_update = '''
  let g:syntastic_mode_map = { 'mode': 'passive',
            \ 'active_filetypes': ['ruby'] }
  let g:syntastic_ruby_checkers = ['rubocop']
'''
