[[plugins]]
repo = 'Shougo/denite.nvim' #バッファ等管理
depends = ['nvim-yarp', 'vim-hug-neovim-rpc']
hook_post_source = '''
  let g:unite_enable_start_insert=1
  let g:unite_source_history_yank_enable=1
  let g:unite_source_file_mru_limit = 200

  call denite#custom#var('file/rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', '', '--hidden'])
  call denite#custom#var('grep', 'command', ['ag'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', [])

  let s:ignore_globs = ['.git', '.svn', 'node_modules']

  "ag のレベルで検索対象からはずす
  call denite#custom#var('file/rec', 'command', [
        \ 'ag',
        \ '--follow',
        \ ] + map(deepcopy(s:ignore_globs), { k, v -> '--ignore=' . v }) + [
        \ '--nocolor',
        \ '--nogroup',
        \ '-g',
        \ ''
        \ ])

  call denite#custom#source('file/rec', 'matchers', ['matcher/substring'])

  " 他のソース向けに ignore_globs 自体は初期化
  call denite#custom#filter('matcher/ignore_globs', 'ignore_globs', s:ignore_globs)

  nnoremap <silent> ,f :<C-u>DeniteWithBufferDir -buffer-name=files file<CR>
  nnoremap <silent> ,r :<C-u>Denite -buffer-name=register register<CR>
  nnoremap <silent> ,u :<C-u>Denite file_mru buffer<CR>
  nnoremap <C-g> :<C-u>Denite grep<cr>
  nnoremap <C-b> :<C-u>Denite buffer<CR>
  nnoremap <C-p> :<C-u>Denite file/rec<CR>

  autocmd FileType denite call s:denite_my_settings()
  function! s:denite_my_settings() abort
    nnoremap <silent><buffer><expr> <CR>
    \ denite#do_map('do_action')
    nnoremap <silent><buffer><expr> d
    \ denite#do_map('do_action', 'delete')
    nnoremap <silent><buffer><expr> p
    \ denite#do_map('do_action', 'preview')
    nnoremap <silent><buffer><expr> q
    \ denite#do_map('quit')
    nnoremap <silent><buffer><expr> i
    \ denite#do_map('open_filter_buffer')
    nnoremap <silent><buffer><expr> <Space>
    \ denite#do_map('toggle_select').'j'
    nnoremap <silent><buffer><expr> <C-s>
    \ denite#do_map('do_action', 'split')
    nnoremap <silent><buffer><expr> <C-v>
    \ denite#do_map('do_action', 'vsplit')
  endfunction

  autocmd FileType denite-filter call s:denite_filter_my_setting()
  function! s:denite_filter_my_setting() abort
    inoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
    " 一つ上のディレクトリを開き直す
    inoremap <silent><buffer><expr> <BS> denite#do_map('move_up_path')
    " Denite を閉じる
    inoremap <silent><buffer><expr> <C-c> denite#do_map('quit')
    nnoremap <silent><buffer><expr> <C-c> denite#do_map('quit')
  endfunction
'''
