[[plugins]]
repo = 'roxma/nvim-yarp'
if = ''' ! has('nvim')'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = ''' ! has('nvim')'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']
hook_add = '''
source ~/dotfiles/.vim/lazys/vue.vim
'''

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['vue']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
source ~/dotfiles/.vim/lazys/vim-go.vim
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_add = '''
source ~/dotfiles/.vim/lazys/vim-markdown.vim
'''

[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']
